- name: Install curl
  ansible.builtin.package:
    name: curl
    state: present

- name: Install wget
  ansible.builtin.package:
    name: wget
    state: present

- name: Install xz
  package:
    name: "{{ xz }}"
    state: present

- name: Download and run the Nix install script
  ansible.builtin.shell: |
    wget https://nixos.org/nix/install -O /tmp/install
    echo "y" | bash /tmp/install --daemon
  ignore_errors: yes

- name: Add Nix profile to shell configuration
  ansible.builtin.lineinfile:
    dest: $HOME/.bashrc
    line: "source $HOME/.nix-profile/etc/profile.d/nix.sh"

- name: Add a cross user environment variable
  ansible.builtin.shell: echo "PATH=$PATH:$HOME/.nix-profile/bin" > /etc/environment
  become: yes

- name: Reset connection to refresh the environment variables
  meta: reset_connection

- name: Check if the nix configuration directory exists
  ansible.builtin.stat:
    path: $HOME/.config/nix
  register: nix_dir

- name: Create nix configuration directory
  ansible.builtin.file:
    path: $HOME/.config/nix
    state: directory
    mode: 0755
    recurse: yes
  when: nix_dir.stat.exists == false

- name: Add Nix configuration file
  ansible.builtin.lineinfile:
    dest: $HOME/.config/nix/nix.conf
    line: experimental-features = nix-command flakes
    create: yes

- name: Install git
  ansible.builtin.shell: nix-env -iA nixpkgs.git

- name: Install gcc
  ansible.builtin.shell: nix-env -iA nixpkgs.gcc

- name: Install make
  ansible.builtin.shell: nix-env -iA nixpkgs.gnumake
