- name: Install fish package + others
  ansible.builtin.shell: nix-env -iA nixpkgs.{{ item }}
  loop:
    - fish
    - exa

- name: Check if the fish configuration directory exists
  ansible.builtin.stat:
    path: $HOME/.config/fish
  register: fish_home_dir

- name: Ansible create directory the fish configuration directory if not exists
  ansible.builtin.file:
    path: $HOME/.config/fish
    state: directory
    mode: 0755
    recurse: yes
  when: fish_home_dir.stat.exists == false

- name: Copy the fish configuration directory
  ansible.builtin.copy:
    src: fish
    dest: $HOME/.config
    force: yes

- name: Download oh-my-fish install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    dest: /tmp/install

- name: Install oh-my-fish
  ansible.builtin.shell: fish /tmp/install --yes --noninteractive

- name: Install oh-my-fish plugins
  ansible.builtin.shell: fish -c "omf install {{ item }}"
  loop:
    - bobthefish
    - peco
    - bang-bang
    - fish_logo

# The shell path is hardcoded because `$(which fish)` cannot locate fish for some reasons
- name: Set fish as the default shell
  ansible.builtin.shell: |
    usermod --shell $(which fish) {{ ansible_user }}
  become: yes
